<a href="https://colab.research.google.com/github/jaeohshin/keras/blob/main/tutorial4_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Here we discuss a few fundamenal issues on machine learning, such as what it means to learn, over-fitting, under-fitting, and sveral ways of controlling them.

In [2]:
# First, I change the learning rate.
# I copied the same function from previous example on the image recognition.

from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()



11490434/11490434 [==============================] - 0s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
test_images.shape

(10000, 28, 28)

In [9]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
                          ])

In [11]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [13]:
# preparing the image data
train_images = train_images.reshape( (60000, 28*28 ))
train_images = train_images.astype("float32")/ 255

test_images = test_images.reshape( (10000, 28*28 ))
test_images = test_images.astype("float32")/ 255

In [14]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 7s 3ms/step - loss: 2.2369 - accuracy: 0.2544
Epoch 2/5
469/469 [==============================] - 1s 3ms/step - loss: 1.6744 - accuracy: 0.5926
Epoch 3/5
469/469 [==============================] - 2s 4ms/step - loss: 1.0458 - accuracy: 0.7475
Epoch 4/5
469/469 [==============================] - 2s 4ms/step - loss: 0.7490 - accuracy: 0.8096
Epoch 5/5
469/469 [==============================] - 1s 3ms/step - loss: 0.6043 - accuracy: 0.8412


In [18]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)

1/1 [==============================] - 0s 20ms/step


In [19]:
predictions[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [20]:
predictions[0].argmax()

7

In [21]:
test_labels[0]

7